-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 17:15:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Adhérent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adhérent` (
  `idAdhérent` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(120) NOT NULL,
  `telephone` VARCHAR(12) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `derniereVisite` DATE NULL,
  `derniereInscription` DATE NULL,
  `niveauPratique` VARCHAR(45) NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`idAdhérent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(12) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Circuit` (
  `idCircuit` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(120) NOT NULL,
  `nbrMaxPlace` INT NOT NULL,
  `disponible` TINYINT NOT NULL,
  PRIMARY KEY (`idCircuit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Réservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Réservation` (
  `idRéservation` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `heureDebut` TIME NOT NULL,
  `heureFin` TIME NOT NULL,
  `nombreParticipant` INT NOT NULL,
  `Adhérent_idAdhérent` INT NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Circuit_idCircuit` INT NOT NULL,
  PRIMARY KEY (`idRéservation`),
  INDEX `fk_Réservation_Adhérent1_idx` (`Adhérent_idAdhérent` ASC) VISIBLE,
  INDEX `fk_Réservation_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Réservation_Circuit1_idx` (`Circuit_idCircuit` ASC) VISIBLE,
  CONSTRAINT `fk_Réservation_Adhérent1`
    FOREIGN KEY (`Adhérent_idAdhérent`)
    REFERENCES `mydb`.`Adhérent` (`idAdhérent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Réservation_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Réservation_Circuit1`
    FOREIGN KEY (`Circuit_idCircuit`)
    REFERENCES `mydb`.`Circuit` (`idCircuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `idMatch` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `heureDebut` TIME NOT NULL,
  `heureFin` TIME NOT NULL,
  `nbrPartNecessaire` INT NOT NULL,
  `gagnant` INT NULL,
  `resultatFinal` VARCHAR(45) NULL,
  `Circuit_idCircuit` INT NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Adhérent_idAdhérent` INT NOT NULL,
  PRIMARY KEY (`idMatch`),
  INDEX `gagnant_idx` (`gagnant` ASC) VISIBLE,
  INDEX `fk_Match_Circuit1_idx` (`Circuit_idCircuit` ASC) VISIBLE,
  INDEX `fk_Match_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Match_Adhérent1_idx` (`Adhérent_idAdhérent` ASC) VISIBLE,
  CONSTRAINT `gagnant`
    FOREIGN KEY (`gagnant`)
    REFERENCES `mydb`.`Adhérent` (`idAdhérent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Circuit1`
    FOREIGN KEY (`Circuit_idCircuit`)
    REFERENCES `mydb`.`Circuit` (`idCircuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Adhérent1`
    FOREIGN KEY (`Adhérent_idAdhérent`)
    REFERENCES `mydb`.`Adhérent` (`idAdhérent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `contenu` LONGTEXT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `dateMAJ` DATE NOT NULL,
  `auteur` INT NOT NULL,
  PRIMARY KEY (`idArticle`, `auteur`),
  INDEX `fk_Article_Admin1_idx` (`auteur` ASC) VISIBLE,
  CONSTRAINT `fk_Article_Admin1`
    FOREIGN KEY (`auteur`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
